services:
  db:
    image: postgres:15-alpine
    container_name: karamazov_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interview_coach
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: .
    container_name: karamazov_api
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/interview_coach
    ports:
      - '8000:8000'
    restart: always

volumes:
  postgres_data:
